### ISSUE TITLE
Access to Github Actions large runners

### ISSUE THREAD

**Issue by annetill** [lf-energy/tac#146]
For Powsybl project, we need native build for some parts of the library (`powsybl-open-loadlfow` and `pypowsybl`). We already support Linux 64, Windows 64 and MacOS AMD 64. In addition, many of our users request a MacOS ARM 64 support because it is the processors architecture for all new MacOS machines since three years. The only way to access to a build for MacOS ARM 64 is through Github Action Xlarge runners, which is a non-free service.

For more information: 
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners

**Comment by eroussy** [comment]
Hi

This is also a need we share for the SEAPATH project.
In order to complete our CI process, we need to build the entire SEAPATH operating system.
We have made some benchmarks to determine the resources required, and we need about 500 GB of storage, 32 GB of RAM, and 8 cores.
Such specifications are only available on large GitHub runners.

**Comment by geofjamg** [comment]
It seems that since a recent change of GH runners, ARM64 runners for MacOs are freely available for public repositoroes (https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners). We have for that to use the 'macos-14' runner. I will try soon for pypowsybl and if ok we will not have the need anymore for powsybl to acces to larger runners.

**Comment by ebail** [comment]
Hi @jmertic. Could you please share some updates on that ? Do you think we could have access to GH Actions large runners ? That would be great for SEAPATH ! Thanks.

**Comment by jmertic** [comment]
Hi @ebail - I've put in requests for SEAPATH and PowSyBL - will keep both projects updated on status.

**Comment by So-Fras** [comment]
Hi @jmertic! Following on from @geofjamg 's message, the Powsybl project no longer needs large runners since the recent change of GitHub runners.

**Comment by jmertic** [comment]
No worries @So-Fras - I'll keep the request in for now just in case this changes in the future.

**Comment by jmertic** [comment]
This should be done now - thank you all!

**Comment by Paullgk** [comment]
Hello everyone,

In the Seapath project, we are currently planning to set up a Github large runner to build the complete system. However, we are unable to proceed as GitHub indicates that the spending limit has been reached.
![image](https://github.com/user-attachments/assets/498c9205-1909-4ce3-9ef7-50f53873c965)

**Comment by jmertic** [comment]
Hi @Paullgk - can you give us insight into the runners you are looking to use and the projected costs? We can likely get this enabled. Feel free to reach out to me via email jmertic@linuxfoundation.org
